### ISSUE TITLE
Have Cogni Click-To-Advance behave similarly to other RenPy Characters

### ISSUE THREAD

**Issue by hobg0blin** [hobg0blin/dataville#59]

**Comment by habmin** [comment]
Just had a thought. Renpy doesn't seem seem to register any mouse-down inputs at all, only mouse-up. (Looking through forums, people wanting to implement mouse-down had to do it in pygame or pure python to do so). So I'm thinking this issue might be because of the unexpected difference in click-to-advance behavior between the interview characters and Cogni's.

Since the interview characters are regular renpy characters and using the script in a hardcoded renpy manner, their behavior is that as the text shows up, if you click, all the text shows up. Click again, and the script advances. If you wait until all the text is shown and click, the script advances.

Cogni does not behave this way. Since we're calling our own screens, so we have to sort of manually mock a click to advance. Clicking advances the script regardless if the text is still propagating. I tried to make it finish showing the text first, then clicking again to advance the script, but ran into an issue is that if the player waited for the text to fully appear, you then have to click twice to advance the script once, which seemed more cumbersome for players.

I'm wondering if when Lifei said the mouse seemed more sensitive, they were clicking twice and expecting the script to advance once like the interviewers? Can't remember, but maybe Cogni was like this in our old builds?

Either way, I may wait to get more input from our play tests before working on this, but putting down possible solutions:
1. Having a static button for cogni's speech bubble that players have to click to advance the script. Clicking anywhere on the screen will just finish loading the text. 
2. The omni-button doesn't immediately advance the script, it actually checks a screen variable flag that signifies if the text has finished loading first before advancing. If not, set the flag to true and force the text to appear. If already set, advance script. 

How to check if the text is down loading though? Have a timer run that's the string length // cps and set the cta flag to true when completed. Here's how the code might look

```python
screen cogni(what):
	default cta_flag = False
	if not cta_flag:
		timer (len(what) // cps) action SetScreenVariable('cta_flag', True)
	...
	if cta_flag:
		text what # no cps
	else:
		text what # with cps
	...
	button:
		action If('cta_flag', Return(True), toggleScreenVariable('cta_flag'))
```
